### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by cesargrano** [onaluf/fate#39]
Good afternoon, I'm using your component, which by the way is very good, congratulations.

You left with debug (console.log)
fate-editor.js:740 keydown? KeyboardEvent {isTrusted: true, key: "w", code: "KeyW", location: 0, ctrlKey: false, …}

I could take it off.

Thank you.

**Comment by cesargrano** [comment]
The debug is this ..
--> console.info('keydown?', event);

Thank you.

**Comment by onaluf** [comment]
I changed the log level of this one and another from log to debug... I'll investigate what's the best way to strip console.xxx statements completely from the production build later.
