### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'fate-input'.

### ISSUE THREAD

**Issue by Tristan-ow** [onaluf/fate#44]
In Angular 5, I cannot use the editor. I implemented it like in the description

`    <fate-ui ></fate-ui>
    <fate-input [(ngModel)]="data.content"></fate-input>
`
and imported the Module.

But I alwys get the the error

> Can't bind to 'ngModel' since it isn't a known property of 'fate-input'.

**Comment by LeandroHermes** [comment]
You need to import the `FormsModule` from `@angular/forms` too.

``` 
@NgModule({
  // ...
  imports: [
    // ...
    FormsModule,
    FateModule
  ]
  // ...
}) // ...
```

**Comment by onaluf** [comment]
Thanks @LeandroHermes, that should fix @Tristan-ow problem indeed. I'll add that info to the doc and close the issue once it's done...
