### ISSUE TITLE
Mention feature

### ISSUE THREAD

**Issue by omidkh68** [onaluf/fate#47]
is that possible to use mention feature?

**Comment by onaluf** [comment]
If you mean `<blockquote>`, no, not yet. My idea was to add this as an example of how you can customize the editor to support any kind of element. I'll try to release the doc/code example soon.

**Comment by omidkh68** [comment]
@onaluf 
No, in fact, I need the feature to select an user by putting @ in editor such as instagram.

**Comment by onaluf** [comment]
That's an even more interesting example. I'll write the example for that. If you want You can have a look at the way the link function is written, it will give you a basic outline of what needs to be done.

**Comment by omidkh68** [comment]
@onaluf it's great if we can inject a service in editor to show menu list of users and each item in menu has the ability to click.

**Comment by onaluf** [comment]
So I've been working on an example of that and then I realized that what you wanted is probably not exactly what I was working on. I was adding a menu to the toolbar to let you pick you mention.

However, in this case, I think you wanted this to happen inline in the editor: When the user starts typing some special char (@ for example) we display a helper menu. To do that I will need to add this feature to the editor but I think it would be a very convenient thing to do ! I'll use this issue to add this feature.

I will push the repo with the example/doc for the custom toolbar entry.

**Comment by omidkh68** [comment]
@onaluf 
Thank you so much, yes I'm looking for inline mode, is that ready to use or not yet?

**Comment by onaluf** [comment]
Quick update: I’m still working on this and it should be ready soonish... probably in the next week or two. Sorry but I haven’t had much bandwidth lately.

**Comment by onaluf** [comment]
I've implemented this feature (finally), to use it on the demo page you can start by typing @ and it will show a menu. To see the implementation detail you can look at all the files with the prefix `example-` in the repo. They should give you a good idea about what is needed.

If you're missing something or need some better explanation, just create a new issue!

**Comment by omidkh68** [comment]
Do you have a plan for navigate into mention menu by keyboard arrow keys?

**Comment by onaluf** [comment]
Yes I had that in mind but it needs some more work... I want it to be as flexible as possible for the implementers of custom contextual menus. I have a few issues to fix but after that I'll work on this!

**Comment by onaluf** [comment]
It's done, you can now use up/down/enter to manipulate the contextual menu.
