### ISSUE TITLE
Angular Versions Colliding 

### ISSUE THREAD

**Issue by sandiphob** [onaluf/fate#53]
This editor is really awesome!! I've gone through many editors and this one hits the mark, while leaving it open to customization.

The only issue I had was that I am on Angular 7 and the Fate-Editor Package is importing Angular 6 as a dependency which causes a "Cannot redeclare block-scoped variable 'ngDevMode'" error when compiling the app. I deleted the angular 6 node from the fate-editor package and resolved my issue but. I tried to do some research and below is what I could find as a possible root cause.

https://github.com/angular/angular/issues/21925#issuecomment-364306640

Thank you so much!!

**Comment by onaluf** [comment]
This should work now... I just saw by testing that you need to have`@angular/material` installed for the code to compile, even if you don't want to use the material version of the editor. I'll try to fix that too soon.
