### ISSUE TITLE
fate-material "required" attribute has no effect

### ISSUE THREAD

**Issue by ghost** [onaluf/fate#67]
When using fate-material in an angular form, the "required" attribute has no effect on the text field. I'd love to at least having the asterisk following the placeholder (e.g. "Placeholder*").

Example of what I'm trying to do:
```
<fate-material placeholder="Content"
               formControlName="contentCtrl"
               [buttons]="editorButtons"
               required></fate-material>
```

**Comment by onaluf** [comment]
fixed in v1.10.1

**Comment by onaluf** [comment]
Well that didn't work, not sure why I thought it did...

**Comment by onaluf** [comment]
reopened the wrong issue

**Comment by JGMAGNO** [comment]
any update on this?

**Comment by onaluf** [comment]
I thought this was fixed, I'll have a look...
