### ISSUE TITLE
Error on build with fate-editor

### ISSUE THREAD

**Issue by innovativeinc-mhummert** [onaluf/fate#70]
I installed the latest version from npm (v1.10.1), and it had the following build errors:

```
WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 335:44-62
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 576:44-62
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 591:40-58
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 626:38-56
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 1351:46-64
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/fate-editor/fesm5/fate-editor.js 1594:54-72
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
```

I changed all instances of `ɵɵdefineInjectable` to `defineInjectable` in fesm5/fate-editor.js, and it compiled with no issues. I don't have the repo set up, so I can't do a merge request right now.

**Comment by onaluf** [comment]
Are you using Angular 8 ? From 1.10.0 and up you need at least Angular 8...

**Comment by innovativeinc-mhummert** [comment]
Whoops, I totally missed that version upgrade the other day. I'll update to Angular 8.

Odd though that it let me install with no warnings on Angular 7. Either way, I'm good to go. Thanks!

**Comment by innovativeinc-mhummert** [comment]
I've confirmed that upgrading to Angular 8 fixes the issue. Apologies for the oversight, and thanks for the input!
