### ISSUE TITLE
FateModule needs @angular/material/form-field

### ISSUE THREAD

**Issue by Applicafroguy** [onaluf/fate#72]
- I am not using @angular/material for my project

This is the error when I import `FateModule`

> /node_modules/fate-editor/fesm2015/fate-editor.js
> Module not found: Error: Can't resolve '@angular/material/form-field'

**Comment by onaluf** [comment]
I’ll try to reproduce this. You shouldn’t needed to use material if you don’t want to!

**Comment by linusbrolin** [comment]
@onaluf I'm still getting error even in 2.0.0 when compiling:
```
ERROR in node_modules/fate-editor/app/fate-material/fate-material.component.d.ts(3,37): error TS2307: Cannot find module '@angular/material/form-field'.
```
I'm using angular 7.2 and a clean default install of fate

**Comment by linusbrolin** [comment]
I did not import the FateMaterialModule.
Unfortunately I cannot test with Angular 8 at the moment, because it requires a later Node version and I have a very big work project on Angular 7 that cannot be upgraded to 8 or 9 just yet. :/

So for now I guess I'm gonna have to downgrade to fate 1.9.3 and install material.

**Comment by onaluf** [comment]
I’ll try to reproduce the issue and see if I can fix it for angular 7.
There should be a way.

**Comment by onaluf** [comment]
So @linusbrolin I've tested and indeed it's not working, not for 7.0 but nor for other versions... not sure why I thought it did. I'll work some more on this.

**Comment by linusbrolin** [comment]
Alright, thank you.

**Comment by onaluf** [comment]
I think this issue has been fixed in the last release, please check if it work for you and if it doesn't, comment here and  I'll reopen this issue!
