### ISSUE TITLE
Angular 9 compatibility issues

### ISSUE THREAD

**Issue by Void-0** [onaluf/fate#73]
I tried updating my project to Angular 9 and I've discovered that fate isn't 100% compatible with the new version. Basically the input can't be focused with the mouse as well as any interaction with the text inside doesn't work.
Interacting with the popup (material ui) works just fine as well as any keyboard input/selection.
Other then that the component seems to work fine.

**Comment by onaluf** [comment]
I haven‘t tested the editor with Ivy yet... I’ll fix that ASAP!
