### ISSUE TITLE
after updating to Angular 9.0.0 fate is not working

### ISSUE THREAD

**Issue by Applicafroguy** [onaluf/fate#75]
I am using fate-editor 2.0.0

My setup
    ```
<mat-form-field appearance="outline">
    <mat-label>Name</mat-label>
    <fate-material formControlName="name"
                placeholder="....">
            </fate-material>
</mat-form-field>
```
**This is the error I get**
"this.selectionRange is undefined"
checkForDropdownContext fate-editor.js:1138
ngAfterViewInit fate-editor.js:878

**Comment by onaluf** [comment]
I think this is the same issue as #73 . It looks like it’s related to the switch to Ivy. I’ll try to spend some time in this soon!
