### ISSUE TITLE
<br> after text with inline tags causes last part of text to split to newline

### ISSUE THREAD

**Issue by linusbrolin** [onaluf/fate#76]
The linebreak handling added in pull https://github.com/onaluf/fate/pull/65 causes text that contains any form of inline tags (b, i, em, u, s, strike, span, etc, etc) to be split into multiple lines.

For example:
if the inline text is as follows:
```
test<i>text</i>inline
```
and a `<br>` is added to the end of that line, then the result will become:
```
test<i>text</i><div>inline</div>
```

Easy way to reproduce:
Start with this text:
```
test<i>text</i>inline
```
Then toggle ON either `ul` or `ol` on that line.
Then toggle OFF the `ul` or `ol` again on that same line.
watch the output.

**Comment by onaluf** [comment]
Ok I understand what's going on, that was a stupid mistake on my part. I'll fix it!
